appName: payment
params: "prod.payment.cart_host prod.payment.cart_port prod.payment.user_host prod.payment.user_port prod.payment.amqp_host prod.payment.amqp_user prod.payment.amqp_pass"
appPort: 8080

resources: 
  limits:
    cpu: 500m
    memory: 712Mi
  requests:
    cpu: 300m
    memory: 512Mi